### PR TITLE
Some QoL improvements and fixes for live Confluent Schema Registry

### LINKED ISSUE #2: Confluent Schema Registry needs a "schema" element as a string
The confluent schema registry takes a single "schema" element which contains the escaped JSON string of the schema.

Fix proposed in upcoming PR.

### PR DESCRIPTION
**Pull request by kitsuneninetails**
Fixes a couple issues in contacting a live Confluent Schema Registry.  Also adds some minor quality-of-life improvements to some of the side-APIs.

Fixes #2 #3 #4 #6

### CODE REVIEW

**Comment by kitsuneninetails** [comment]
This lib has been a lifesaver for me and aside from a couple issues connecting to the kafka schema-registry, this has saved me a lot of time and effort!  Thanks!  Let me know if something int he PR should be updated or added!

**Comment by kitsuneninetails** [comment]
Looks like there are failing tests in this PR.  I will fix and commit to the PR.

**Comment by gklijs** [comment]
I'll try to finish integration tests next weekend. If these are also fixed it might be time for a 1.0.0 release.

**Comment by kitsuneninetails** [comment]
It looks like the failures were rustdoc test failures.  I fixed the docs up and have this running locally.  I'll also look at the README and make sure everything is updated if needed.

**Comment by kitsuneninetails** [comment]
As for release, I don't know if a 1.0.0 or another 0.X version is best, but either way, a new create release would be very helpful for me, as I can then switch back to using the crate, rather than a `{git =""}` dependency. :)

**Pull request merged**
