### PR TITLE
encode value

### PR DESCRIPTION
**Pull request by sfsf9797**
Make sure there is an related issues, and the docs and unit tests are also updated.

### CODE REVIEW

**Comment by gklijs** [comment]
@sfsf9797 Can you please resolve the conflict? Ci should work again, and than we can merge and have a new release soon.

**Comment by sfsf9797** [comment]
Hi @gklijs fixed that

**Comment by sfsf9797** [comment]
btw do we have any timeline for the next release which would include this PR?

**Comment by gklijs** [comment]
I hope this weekend. There is one additional pr I want to merge.

**Pull request merged**
