### PR TITLE
Update apache-avro requirement from ^0.16 to ^0.17

### PR DESCRIPTION
**Pull request by mdroogh**
Update the ci to use "docker compose" instead of "docker-compose"

Make sure there is an related issues, and the docs and unit tests are also updated.

### CODE REVIEW

**Comment by martin-g** [comment]
You could run the workflow if you open a PR in your fork. Once you are ready with the fixes you can open a PR against upstream like this one.

**Comment by mdroogh** [comment]
Clear!

Thanks, I am not that familiar with github workflows, but will give it a go.

**Comment by mdroogh** [comment]
@martin-g in my own repo I ran the workflow, worked as expected.

Can separate the change to be just the `run: docker compose up -d` change if that makes more sense and let the dependabot bump the dependency?

**Comment by martin-g** [comment]
> Can separate the change to be just the `run: docker compose up -d` change if that makes more sense and let the dependabot bump the dependency?

It is up to @gklijs !

**Comment by gklijs** [comment]
Yes, want to do this for some time, but busy with new job, new house, and almost starting an intensive bass course. I hope I have some time this weekend.

**Comment by gklijs** [comment]
Seems like I need to do a bit of work on codecov, but this PR is fine.

**Comment by mdroogh** [comment]
Understandable!

If you create a ticket, or indicate what codecov work needs to be done, I am happy to take a look!

**Comment by gklijs** [comment]
Seems like I just need to create a token and add it as a secret. So should be easy, and likely something only I can do.

**Pull request merged**
